import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>AwwardSite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className='h-16 '>
        <ul className='flex flex-row h-16 bg-slate-200 divide-x divide-gray-400'>
          <li className='flex basis-5% grow-0 w-24  justify-center '><Image 
          src = "/menu.svg"
          height = {24}
          width = {24}
          alt = 'menu logo'
          />
          <span className='my-auto font-mono px-2'>MENU</span>
          </li>
          <li className='flex basis-85%  justify-between w-9/12 '>
            <section className='justify-self-start my-auto px-4'>
              <Image
              src = "/search.svg"
              height = {18}
              width = {18}
              alt = 'search logo'
              />
            </section>
            <section className='my-auto '>
              <span className='text-2xl font-serif'> AWWARDSITE.</span>
            </section>
            <section className='my-auto px-4'>
              <p>are you a member?<a className='font-serif text-lg'>Register/Login</a></p>
            </section>
          </li>
          <li className='text-white bg-gray-900 basis-10% grow w-2/12 flex '><p className='m-auto font-mono'>SUBMIT YOUR SITE!</p></li>
        </ul>
      </nav>
      <section className=''>
        <Image
        src= "/drone2.jpg"
        height = {1080}
        width = {2160}
        alt = "homepage image"
        />
      </section>

      <footer>

      </footer>
    </div>
  )
}
