import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>AwwardSite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='relative'>
        <nav className='h-16 fixed z-10 top-0 right-0 left-0  '>
          <ul className='flex flex-row h-16 bg-slate-200 divide-x divide-gray-400 shadow-xl'>
            <li className='flex basis-5% grow-0 w-24  justify-center '><Image 
            src = "/menu.svg"
            height = {24}
            width = {24}
            alt = 'menu logo'
            />
            <span className='my-auto font-mono px-2'>MENU</span>
            </li>
            <li className='flex basis-85%  justify-between w-9/12 '>
              <section className='justify-self-start my-auto px-4'>
                <Image
                src = "/search.svg"
                height = {18}
                width = {18}
                alt = 'search logo'
                />
              </section>
              <section className='my-auto pl-80 '>
                <span className='text-4xl font-serif text-center'> AWWARDSITE.</span>
              </section>
              <section className='my-auto px-4'>
                <p>are you a member?<a className='font-serif text-lg'>Register/Login</a></p>
              </section>
            </li>
            <li className='text-white bg-gray-900 basis-10% grow w-2/12 flex '><p className='m-auto font-mono'>SUBMIT YOUR SITE!</p></li>
          </ul>
        </nav>
      </section>
      
      <section className='group flex relative bg-black '>
        <Image
        className='flex absolute group-hover:opacity-75 transition-all ease-in-out duration-500'
        src= "/drone2.jpg"
        height = {720}
        width = {2160}
        alt = "homepage image"
          />          

        <section className='flex flex-col absolute text-white justify-around  w-full h-full '>
          <div className='flex  flex-row mt-10 mx-20 justify-between'>
            <div>Site of the Day    September 13,2022</div>
            <div className='fill-white '>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-6 h-6">
                <path strokeLinecap="round" strokeLinejoin="round" d="M7.217 10.907a2.25 2.25 0 100 2.186m0-2.186c.18.324.283.696.283 1.093s-.103.77-.283 1.093m0-2.186l9.566-5.314m-9.566 7.5l9.566 5.314m0 0a2.25 2.25 0 103.935 2.186 2.25 2.25 0 00-3.935-2.186zm0-12.814a2.25 2.25 0 103.933-2.185 2.25 2.25 0 00-3.933 2.185z" />
              </svg>

            </div>
          </div>
          <div className='mx-auto'>
            <section className='text-center text-4xl text-bold font-bold'>Henry Northington</section>
            <section className='text-sm'>BY <span className='text-blue-200 font-semibold'>MASON PAJUNAS</span> FROM UNITED STATES WITH 7.35</section>
            <section className='flex flex-row mt-5'>
              <div className='flex flex-col relative'>
                <span className='rounded-r-full rounded-b-full rounded-t-full border-4 border-red-400 border-l-red-400/0 w-20 h-20 text-center py-5 text-xl'>7.44</span>
                <span className='text-xs text-center'>DESIGN</span>
              </div>
              <div className='flex flex-col relative'>
                <span className='rounded-r-full rounded-b-full rounded-l-full border-4 border-yellow-400 border-t-red-400/0 w-20 h-20 text-center py-5 text-xl'>7.75</span>
                <span className='text-xs text-center'>USABILITY</span>
              </div>
              <div className='flex flex-col relative'>
                <span className='rounded-r-full rounded-b-full rounded-t-full border-4 border-green-400 border-l-red-400/0 w-20 h-20 text-center py-5 text-xl'>6.95</span>
                <span className='text-xs text-center'>CREATIVITY</span>
              </div>
              <div className='flex flex-col relative'>
                <span className='rounded-r-full rounded-b-full rounded-t-full border-4 border-purple-400 border-l-red-400/0 w-20 h-20 text-center py-5 text-xl'>7.44</span>
                <span className='text-xs text-center'>CONTENT</span>
              </div>
            </section>
          </div>
          <div className='flex flex-row justify-between mx-20'>
            <div className='flex flex-row'>
              <div className='rounded-full bg-blue-300 text-sm px-2   border border-white/0'>Visit Site</div>
              <div className='rounded-full text-sm px-3 ml-5 border-white border  '>Collect</div>
            </div>
            <div>
              <div className='rounded-full text-sm border border-white px-2'>Jury Votes</div>
            </div>
          </div>
        </section>
      </section>
      <section>
        <section className='mx-20 my-10'>
          <div className='my-10 flex flex-row '>
            <div className='text-lg font-semibold'>Sites of the day</div>
            <div className='my-auto mx-2'>Previous Winners</div>
          </div>

          <section className='flex flex-row justify-between'>
            <div className =' group hover:-translate-y-2  flex flex-col divide-y divide-gray-200 w-72 shadow-xl hover:shadow-2xl transition-all duration-300 ease-in-out'>
              <div className = 'relative flex item-center justify-center relative overflow-hidden bg-black '>
                <Image
                 className='scale-100 absolute w-full h-full transition-all duration-300 ease-in-out group-hover:scale-125 group-hover:opacity-50'
                 src = "/mrBeast.png"
                 height = {220}
                 width = {290}
                 alt = 'search logo'               
                />
                <section className='opacity-0 group-hover:opacity-100 flex flex-col absolute justify-between my-5 w-full h-full px-5 pb-10 transition-all duration-300 ease-in-out'>
                  <div className='flex flex-row stroke-white fill-white stroke text-white justify-between' >
                    <div className='flex flex-row '>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.266333 10.967571 12.541024 8.3125 12.933594 L 8.3125 9.0898438 L 9.8652344 9.0898438 L 10.109375 7.5136719 L 8.3125 7.5136719 L 8.3125 6.6503906 C 8.3125 5.9953906 8.5256719 5.4140625 9.1386719 5.4140625 L 10.123047 5.4140625 L 10.123047 4.0371094 C 9.9500469 4.0141094 9.5845781 3.9628906 8.8925781 3.9628906 C 7.4485781 3.9628906 6.6015625 4.7258906 6.6015625 6.4628906 L 6.6015625 7.5117188 L 5.1171875 7.5117188 L 5.1171875 9.0898438 L 6.6035156 9.0898438 L 6.6035156 12.919922 C 3.9897868 12.492118 2 10.237066 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.543488 10.543488 13 7.5 13 C 4.4565116 13 2 10.543488 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z M 9.1113281 4.7519531 C 8.2683281 4.7519531 7.5820312 5.4353438 7.5820312 6.2773438 C 7.5820312 6.4343438 7.6367188 6.5395312 7.6367188 6.6445312 C 6.3727188 6.5925313 5.3229375 5.895 4.5859375 5 C 4.4279375 5.211 4.375 5.4733281 4.375 5.7363281 C 4.375 6.2623281 4.5799531 6.8419375 5.0019531 7.2109375 C 4.7219531 7.1729375 4.586 7.105 4.375 7 C 4.375 7.737 4.8442969 8.2248125 5.5292969 8.3828125 C 5.5292969 8.3828125 5.2654219 8.4355469 5.1074219 8.4355469 C 4.9874219 8.4355469 4.84375 8.3828125 4.84375 8.3828125 C 5.05475 8.9618125 5.580625 9.4335938 6.265625 9.4335938 C 5.739625 9.8025937 5.0541406 10 4.3691406 10 L 4 10 C 4.375 10.5 5.2494063 10.750953 6.3164062 10.751953 C 9.1074063 10.751953 10.636719 8.4355469 10.636719 6.4355469 L 10.636719 6.2246094 C 10.900719 6.0136094 11.163 5.7505469 11.375 5.4355469 C 11.059 5.5935469 10.796469 5.6442656 10.480469 5.6972656 C 10.796469 5.4872656 11.059062 5.2234688 11.164062 4.8554688 C 10.901063 5.0124687 10.585797 5.1716094 10.216797 5.2246094 C 9.9527969 4.9096094 9.5333281 4.7519531 9.1113281 4.7519531 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 4.457031 4.457031 2 7.5 2 Z M 5.5 5 C 4.125 5 3 6.125 3 7.5 C 3 8.875 4.125 10 5.5 10 C 6.875 10 8 8.875 8 7.5 L 8 7 L 6 7 L 6 8 L 6.796875 8 C 6.578125 8.554688 6.136719 9 5.5 9 C 4.664063 9 4 8.335938 4 7.5 C 4 6.664063 4.664063 6 5.5 6 C 5.882813 6 6.222656 6.140625 6.488281 6.371094 L 7.148438 5.621094 C 6.707031 5.234375 6.128906 5 5.5 5 Z M 10 6 L 10 7 L 9 7 L 9 8 L 10 8 L 10 9 L 11 9 L 11 8 L 12 8 L 12 7 L 11 7 L 11 6 Z"/></svg>                      
                    </div> 
                    <div className='flex '>
                     <div className='rounded-full px-2 text-sm border border-white'>Collect</div>                       
                    </div> 
                  </div>
                  <div className='fill-white stroke-white flex justify-end'>
                    <svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1.035156 C 3.917969 1.035156 1 3.941406 1 7.515625 L 1 8 L 2 8 L 2 7.515625 C 2 4.484375 4.457031 2.035156 7.5 2.035156 C 9.132813 2.035156 10.589844 2.75 11.59375 3.875 L 10.464844 5 L 14 5 L 14 1.476563 L 12.300781 3.167969 C 11.113281 1.863281 9.40625 1.035156 7.5 1.035156 Z M 13 7 L 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 5.859375 13 4.402344 12.277344 3.394531 11.140625 L 4.535156 10 L 1 10 L 1 13.535156 L 2.6875 11.847656 C 3.878906 13.164063 5.589844 14 7.5 14 C 11.085938 14 14 11.085938 14 7.5 L 14 7 Z"/></svg>
                  </div>
                </section>
              </div>
              <div className = 'flex flex-col mx-5'>
                <span className='font-serif my-2'>Karina Sirqueira Gallery</span>
                <div className='flex flex-row justify-between'>
                  <span className=' text-xs mb-5'>From United States</span>
                  <span className=' text-xs'>September 11, 2022</span>
                </div>

              </div>
              <div className = 'flex mx-5 ' >
                <Image
                 className='rounded-full overflow-hidden' 
                 src = "/avatar.jpeg"
                 height = {18}
                 width = {32}
                 alt = 'search logo'                 
                />
                <p className='font-serif text-xs my-2 mx-2'>BY KARINA SIRQUEIRA</p>
              </div>
            </div>
            <div className =' group hover:-translate-y-2  flex flex-col divide-y divide-gray-200 w-72 shadow-xl hover:shadow-2xl transition-all duration-300 ease-in-out'>
              <div className = 'relative flex item-center justify-center relative overflow-hidden bg-black '>
                <Image
                 className='scale-100 absolute w-full h-full transition-all duration-300 ease-in-out group-hover:scale-125 group-hover:opacity-50'
                 src = "/mrBeast.png"
                 height = {220}
                 width = {290}
                 alt = 'search logo'               
                />
                <section className='opacity-0 group-hover:opacity-100 flex flex-col absolute justify-between my-5 w-full h-full px-5 pb-10 transition-all duration-300 ease-in-out'>
                  <div className='flex flex-row stroke-white fill-white stroke text-white justify-between' >
                    <div className='flex flex-row '>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.266333 10.967571 12.541024 8.3125 12.933594 L 8.3125 9.0898438 L 9.8652344 9.0898438 L 10.109375 7.5136719 L 8.3125 7.5136719 L 8.3125 6.6503906 C 8.3125 5.9953906 8.5256719 5.4140625 9.1386719 5.4140625 L 10.123047 5.4140625 L 10.123047 4.0371094 C 9.9500469 4.0141094 9.5845781 3.9628906 8.8925781 3.9628906 C 7.4485781 3.9628906 6.6015625 4.7258906 6.6015625 6.4628906 L 6.6015625 7.5117188 L 5.1171875 7.5117188 L 5.1171875 9.0898438 L 6.6035156 9.0898438 L 6.6035156 12.919922 C 3.9897868 12.492118 2 10.237066 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.543488 10.543488 13 7.5 13 C 4.4565116 13 2 10.543488 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z M 9.1113281 4.7519531 C 8.2683281 4.7519531 7.5820312 5.4353438 7.5820312 6.2773438 C 7.5820312 6.4343438 7.6367188 6.5395312 7.6367188 6.6445312 C 6.3727188 6.5925313 5.3229375 5.895 4.5859375 5 C 4.4279375 5.211 4.375 5.4733281 4.375 5.7363281 C 4.375 6.2623281 4.5799531 6.8419375 5.0019531 7.2109375 C 4.7219531 7.1729375 4.586 7.105 4.375 7 C 4.375 7.737 4.8442969 8.2248125 5.5292969 8.3828125 C 5.5292969 8.3828125 5.2654219 8.4355469 5.1074219 8.4355469 C 4.9874219 8.4355469 4.84375 8.3828125 4.84375 8.3828125 C 5.05475 8.9618125 5.580625 9.4335938 6.265625 9.4335938 C 5.739625 9.8025937 5.0541406 10 4.3691406 10 L 4 10 C 4.375 10.5 5.2494063 10.750953 6.3164062 10.751953 C 9.1074063 10.751953 10.636719 8.4355469 10.636719 6.4355469 L 10.636719 6.2246094 C 10.900719 6.0136094 11.163 5.7505469 11.375 5.4355469 C 11.059 5.5935469 10.796469 5.6442656 10.480469 5.6972656 C 10.796469 5.4872656 11.059062 5.2234688 11.164062 4.8554688 C 10.901063 5.0124687 10.585797 5.1716094 10.216797 5.2246094 C 9.9527969 4.9096094 9.5333281 4.7519531 9.1113281 4.7519531 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 4.457031 4.457031 2 7.5 2 Z M 5.5 5 C 4.125 5 3 6.125 3 7.5 C 3 8.875 4.125 10 5.5 10 C 6.875 10 8 8.875 8 7.5 L 8 7 L 6 7 L 6 8 L 6.796875 8 C 6.578125 8.554688 6.136719 9 5.5 9 C 4.664063 9 4 8.335938 4 7.5 C 4 6.664063 4.664063 6 5.5 6 C 5.882813 6 6.222656 6.140625 6.488281 6.371094 L 7.148438 5.621094 C 6.707031 5.234375 6.128906 5 5.5 5 Z M 10 6 L 10 7 L 9 7 L 9 8 L 10 8 L 10 9 L 11 9 L 11 8 L 12 8 L 12 7 L 11 7 L 11 6 Z"/></svg>                      
                    </div> 
                    <div className='flex '>
                     <div className='rounded-full px-2 text-sm border border-white'>Collect</div>                       
                    </div> 
                  </div>
                  <div className='fill-white stroke-white flex justify-end'>
                    <svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1.035156 C 3.917969 1.035156 1 3.941406 1 7.515625 L 1 8 L 2 8 L 2 7.515625 C 2 4.484375 4.457031 2.035156 7.5 2.035156 C 9.132813 2.035156 10.589844 2.75 11.59375 3.875 L 10.464844 5 L 14 5 L 14 1.476563 L 12.300781 3.167969 C 11.113281 1.863281 9.40625 1.035156 7.5 1.035156 Z M 13 7 L 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 5.859375 13 4.402344 12.277344 3.394531 11.140625 L 4.535156 10 L 1 10 L 1 13.535156 L 2.6875 11.847656 C 3.878906 13.164063 5.589844 14 7.5 14 C 11.085938 14 14 11.085938 14 7.5 L 14 7 Z"/></svg>
                  </div>
                </section>
              </div>
              <div className = 'flex flex-col mx-5'>
                <span className='font-serif my-2'>Karina Sirqueira Gallery</span>
                <div className='flex flex-row justify-between'>
                  <span className=' text-xs mb-5'>From United States</span>
                  <span className=' text-xs'>September 11, 2022</span>
                </div>

              </div>
              <div className = 'flex mx-5 ' >
                <Image
                 className='rounded-full overflow-hidden' 
                 src = "/avatar.jpeg"
                 height = {18}
                 width = {32}
                 alt = 'search logo'                 
                />
                <p className='font-serif text-xs my-2 mx-2'>BY KARINA SIRQUEIRA</p>
              </div>
            </div>
            <div className =' group hover:-translate-y-2  flex flex-col divide-y divide-gray-200 w-72 shadow-xl hover:shadow-2xl transition-all duration-300 ease-in-out'>
              <div className = 'relative flex item-center justify-center relative overflow-hidden bg-black '>
                <Image
                 className='scale-100 absolute w-full h-full transition-all duration-300 ease-in-out group-hover:scale-125 group-hover:opacity-50'
                 src = "/mrBeast.png"
                 height = {220}
                 width = {290}
                 alt = 'search logo'               
                />
                <section className='opacity-0 group-hover:opacity-100 flex flex-col absolute justify-between my-5 w-full h-full px-5 pb-10 transition-all duration-300 ease-in-out'>
                  <div className='flex flex-row stroke-white fill-white stroke text-white justify-between' >
                    <div className='flex flex-row '>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.266333 10.967571 12.541024 8.3125 12.933594 L 8.3125 9.0898438 L 9.8652344 9.0898438 L 10.109375 7.5136719 L 8.3125 7.5136719 L 8.3125 6.6503906 C 8.3125 5.9953906 8.5256719 5.4140625 9.1386719 5.4140625 L 10.123047 5.4140625 L 10.123047 4.0371094 C 9.9500469 4.0141094 9.5845781 3.9628906 8.8925781 3.9628906 C 7.4485781 3.9628906 6.6015625 4.7258906 6.6015625 6.4628906 L 6.6015625 7.5117188 L 5.1171875 7.5117188 L 5.1171875 9.0898438 L 6.6035156 9.0898438 L 6.6035156 12.919922 C 3.9897868 12.492118 2 10.237066 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.543488 10.543488 13 7.5 13 C 4.4565116 13 2 10.543488 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z M 9.1113281 4.7519531 C 8.2683281 4.7519531 7.5820312 5.4353438 7.5820312 6.2773438 C 7.5820312 6.4343438 7.6367188 6.5395312 7.6367188 6.6445312 C 6.3727188 6.5925313 5.3229375 5.895 4.5859375 5 C 4.4279375 5.211 4.375 5.4733281 4.375 5.7363281 C 4.375 6.2623281 4.5799531 6.8419375 5.0019531 7.2109375 C 4.7219531 7.1729375 4.586 7.105 4.375 7 C 4.375 7.737 4.8442969 8.2248125 5.5292969 8.3828125 C 5.5292969 8.3828125 5.2654219 8.4355469 5.1074219 8.4355469 C 4.9874219 8.4355469 4.84375 8.3828125 4.84375 8.3828125 C 5.05475 8.9618125 5.580625 9.4335938 6.265625 9.4335938 C 5.739625 9.8025937 5.0541406 10 4.3691406 10 L 4 10 C 4.375 10.5 5.2494063 10.750953 6.3164062 10.751953 C 9.1074063 10.751953 10.636719 8.4355469 10.636719 6.4355469 L 10.636719 6.2246094 C 10.900719 6.0136094 11.163 5.7505469 11.375 5.4355469 C 11.059 5.5935469 10.796469 5.6442656 10.480469 5.6972656 C 10.796469 5.4872656 11.059062 5.2234688 11.164062 4.8554688 C 10.901063 5.0124687 10.585797 5.1716094 10.216797 5.2246094 C 9.9527969 4.9096094 9.5333281 4.7519531 9.1113281 4.7519531 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 4.457031 4.457031 2 7.5 2 Z M 5.5 5 C 4.125 5 3 6.125 3 7.5 C 3 8.875 4.125 10 5.5 10 C 6.875 10 8 8.875 8 7.5 L 8 7 L 6 7 L 6 8 L 6.796875 8 C 6.578125 8.554688 6.136719 9 5.5 9 C 4.664063 9 4 8.335938 4 7.5 C 4 6.664063 4.664063 6 5.5 6 C 5.882813 6 6.222656 6.140625 6.488281 6.371094 L 7.148438 5.621094 C 6.707031 5.234375 6.128906 5 5.5 5 Z M 10 6 L 10 7 L 9 7 L 9 8 L 10 8 L 10 9 L 11 9 L 11 8 L 12 8 L 12 7 L 11 7 L 11 6 Z"/></svg>                      
                    </div> 
                    <div className='flex '>
                     <div className='rounded-full px-2 text-sm border border-white'>Collect</div>                       
                    </div> 
                  </div>
                  <div className='fill-white stroke-white flex justify-end'>
                    <svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1.035156 C 3.917969 1.035156 1 3.941406 1 7.515625 L 1 8 L 2 8 L 2 7.515625 C 2 4.484375 4.457031 2.035156 7.5 2.035156 C 9.132813 2.035156 10.589844 2.75 11.59375 3.875 L 10.464844 5 L 14 5 L 14 1.476563 L 12.300781 3.167969 C 11.113281 1.863281 9.40625 1.035156 7.5 1.035156 Z M 13 7 L 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 5.859375 13 4.402344 12.277344 3.394531 11.140625 L 4.535156 10 L 1 10 L 1 13.535156 L 2.6875 11.847656 C 3.878906 13.164063 5.589844 14 7.5 14 C 11.085938 14 14 11.085938 14 7.5 L 14 7 Z"/></svg>
                  </div>
                </section>
              </div>
              <div className = 'flex flex-col mx-5'>
                <span className='font-serif my-2'>Karina Sirqueira Gallery</span>
                <div className='flex flex-row justify-between'>
                  <span className=' text-xs mb-5'>From United States</span>
                  <span className=' text-xs'>September 11, 2022</span>
                </div>

              </div>
              <div className = 'flex mx-5 ' >
                <Image
                 className='rounded-full overflow-hidden' 
                 src = "/avatar.jpeg"
                 height = {18}
                 width = {32}
                 alt = 'search logo'                 
                />
                <p className='font-serif text-xs my-2 mx-2'>BY KARINA SIRQUEIRA</p>
              </div>
            </div>
            <div className =' group hover:-translate-y-2  flex flex-col divide-y divide-gray-200 w-72 shadow-xl hover:shadow-2xl transition-all duration-300 ease-in-out'>
              <div className = 'relative flex item-center justify-center relative overflow-hidden bg-black '>
                <Image
                 className='scale-100 absolute w-full h-full transition-all duration-300 ease-in-out group-hover:scale-125 group-hover:opacity-50'
                 src = "/mrBeast.png"
                 height = {220}
                 width = {290}
                 alt = 'search logo'               
                />
                <section className='opacity-0 group-hover:opacity-100 flex flex-col absolute justify-between my-5 w-full h-full px-5 pb-10 transition-all duration-300 ease-in-out'>
                  <div className='flex flex-row stroke-white fill-white stroke text-white justify-between' >
                    <div className='flex flex-row '>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.266333 10.967571 12.541024 8.3125 12.933594 L 8.3125 9.0898438 L 9.8652344 9.0898438 L 10.109375 7.5136719 L 8.3125 7.5136719 L 8.3125 6.6503906 C 8.3125 5.9953906 8.5256719 5.4140625 9.1386719 5.4140625 L 10.123047 5.4140625 L 10.123047 4.0371094 C 9.9500469 4.0141094 9.5845781 3.9628906 8.8925781 3.9628906 C 7.4485781 3.9628906 6.6015625 4.7258906 6.6015625 6.4628906 L 6.6015625 7.5117188 L 5.1171875 7.5117188 L 5.1171875 9.0898438 L 6.6035156 9.0898438 L 6.6035156 12.919922 C 3.9897868 12.492118 2 10.237066 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.543488 10.543488 13 7.5 13 C 4.4565116 13 2 10.543488 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z M 9.1113281 4.7519531 C 8.2683281 4.7519531 7.5820312 5.4353438 7.5820312 6.2773438 C 7.5820312 6.4343438 7.6367188 6.5395312 7.6367188 6.6445312 C 6.3727188 6.5925313 5.3229375 5.895 4.5859375 5 C 4.4279375 5.211 4.375 5.4733281 4.375 5.7363281 C 4.375 6.2623281 4.5799531 6.8419375 5.0019531 7.2109375 C 4.7219531 7.1729375 4.586 7.105 4.375 7 C 4.375 7.737 4.8442969 8.2248125 5.5292969 8.3828125 C 5.5292969 8.3828125 5.2654219 8.4355469 5.1074219 8.4355469 C 4.9874219 8.4355469 4.84375 8.3828125 4.84375 8.3828125 C 5.05475 8.9618125 5.580625 9.4335938 6.265625 9.4335938 C 5.739625 9.8025937 5.0541406 10 4.3691406 10 L 4 10 C 4.375 10.5 5.2494063 10.750953 6.3164062 10.751953 C 9.1074063 10.751953 10.636719 8.4355469 10.636719 6.4355469 L 10.636719 6.2246094 C 10.900719 6.0136094 11.163 5.7505469 11.375 5.4355469 C 11.059 5.5935469 10.796469 5.6442656 10.480469 5.6972656 C 10.796469 5.4872656 11.059062 5.2234688 11.164062 4.8554688 C 10.901063 5.0124687 10.585797 5.1716094 10.216797 5.2246094 C 9.9527969 4.9096094 9.5333281 4.7519531 9.1113281 4.7519531 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 4.457031 4.457031 2 7.5 2 Z M 5.5 5 C 4.125 5 3 6.125 3 7.5 C 3 8.875 4.125 10 5.5 10 C 6.875 10 8 8.875 8 7.5 L 8 7 L 6 7 L 6 8 L 6.796875 8 C 6.578125 8.554688 6.136719 9 5.5 9 C 4.664063 9 4 8.335938 4 7.5 C 4 6.664063 4.664063 6 5.5 6 C 5.882813 6 6.222656 6.140625 6.488281 6.371094 L 7.148438 5.621094 C 6.707031 5.234375 6.128906 5 5.5 5 Z M 10 6 L 10 7 L 9 7 L 9 8 L 10 8 L 10 9 L 11 9 L 11 8 L 12 8 L 12 7 L 11 7 L 11 6 Z"/></svg>                      
                    </div> 
                    <div className='flex '>
                     <div className='rounded-full px-2 text-sm border border-white'>Collect</div>                       
                    </div> 
                  </div>
                  <div className='fill-white stroke-white flex justify-end'>
                    <svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1.035156 C 3.917969 1.035156 1 3.941406 1 7.515625 L 1 8 L 2 8 L 2 7.515625 C 2 4.484375 4.457031 2.035156 7.5 2.035156 C 9.132813 2.035156 10.589844 2.75 11.59375 3.875 L 10.464844 5 L 14 5 L 14 1.476563 L 12.300781 3.167969 C 11.113281 1.863281 9.40625 1.035156 7.5 1.035156 Z M 13 7 L 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 5.859375 13 4.402344 12.277344 3.394531 11.140625 L 4.535156 10 L 1 10 L 1 13.535156 L 2.6875 11.847656 C 3.878906 13.164063 5.589844 14 7.5 14 C 11.085938 14 14 11.085938 14 7.5 L 14 7 Z"/></svg>
                  </div>
                </section>
              </div>
              <div className = 'flex flex-col mx-5'>
                <span className='font-serif my-2'>Karina Sirqueira Gallery</span>
                <div className='flex flex-row justify-between'>
                  <span className=' text-xs mb-5'>From United States</span>
                  <span className=' text-xs'>September 11, 2022</span>
                </div>

              </div>
              <div className = 'flex mx-5 ' >
                <Image
                 className='rounded-full overflow-hidden' 
                 src = "/avatar.jpeg"
                 height = {18}
                 width = {32}
                 alt = 'search logo'                 
                />
                <p className='font-serif text-xs my-2 mx-2'>BY KARINA SIRQUEIRA</p>
              </div>
            </div>

          </section>
        </section>
        <section className='mx-20 my-10'>
          <div className='my-10 flex flex-row '>
            <div className='text-lg font-semibold'>Nominees</div>
            <div className='my-auto mx-2'>We need your vote!</div>
          </div>

          <section className='flex flex-row justify-between'>
            <div className =' group hover:-translate-y-2  flex flex-col divide-y divide-gray-200 w-72 shadow-xl hover:shadow-2xl transition-all duration-300 ease-in-out'>
              <div className = 'relative flex item-center justify-center relative overflow-hidden bg-black '>
                <Image
                 className='scale-100 absolute w-full h-full transition-all duration-300 ease-in-out group-hover:scale-125 group-hover:opacity-50'
                 src = "/mrBeast.png"
                 height = {220}
                 width = {290}
                 alt = 'search logo'               
                />
                <section className='opacity-0 group-hover:opacity-100 flex flex-col absolute justify-between my-5 w-full h-full px-5 pb-10 transition-all duration-300 ease-in-out'>
                  <div className='flex flex-row stroke-white fill-white stroke text-white justify-between' >
                    <div className='flex flex-row '>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.266333 10.967571 12.541024 8.3125 12.933594 L 8.3125 9.0898438 L 9.8652344 9.0898438 L 10.109375 7.5136719 L 8.3125 7.5136719 L 8.3125 6.6503906 C 8.3125 5.9953906 8.5256719 5.4140625 9.1386719 5.4140625 L 10.123047 5.4140625 L 10.123047 4.0371094 C 9.9500469 4.0141094 9.5845781 3.9628906 8.8925781 3.9628906 C 7.4485781 3.9628906 6.6015625 4.7258906 6.6015625 6.4628906 L 6.6015625 7.5117188 L 5.1171875 7.5117188 L 5.1171875 9.0898438 L 6.6035156 9.0898438 L 6.6035156 12.919922 C 3.9897868 12.492118 2 10.237066 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.543488 10.543488 13 7.5 13 C 4.4565116 13 2 10.543488 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z M 9.1113281 4.7519531 C 8.2683281 4.7519531 7.5820312 5.4353438 7.5820312 6.2773438 C 7.5820312 6.4343438 7.6367188 6.5395312 7.6367188 6.6445312 C 6.3727188 6.5925313 5.3229375 5.895 4.5859375 5 C 4.4279375 5.211 4.375 5.4733281 4.375 5.7363281 C 4.375 6.2623281 4.5799531 6.8419375 5.0019531 7.2109375 C 4.7219531 7.1729375 4.586 7.105 4.375 7 C 4.375 7.737 4.8442969 8.2248125 5.5292969 8.3828125 C 5.5292969 8.3828125 5.2654219 8.4355469 5.1074219 8.4355469 C 4.9874219 8.4355469 4.84375 8.3828125 4.84375 8.3828125 C 5.05475 8.9618125 5.580625 9.4335938 6.265625 9.4335938 C 5.739625 9.8025937 5.0541406 10 4.3691406 10 L 4 10 C 4.375 10.5 5.2494063 10.750953 6.3164062 10.751953 C 9.1074063 10.751953 10.636719 8.4355469 10.636719 6.4355469 L 10.636719 6.2246094 C 10.900719 6.0136094 11.163 5.7505469 11.375 5.4355469 C 11.059 5.5935469 10.796469 5.6442656 10.480469 5.6972656 C 10.796469 5.4872656 11.059062 5.2234688 11.164062 4.8554688 C 10.901063 5.0124687 10.585797 5.1716094 10.216797 5.2246094 C 9.9527969 4.9096094 9.5333281 4.7519531 9.1113281 4.7519531 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 4.457031 4.457031 2 7.5 2 Z M 5.5 5 C 4.125 5 3 6.125 3 7.5 C 3 8.875 4.125 10 5.5 10 C 6.875 10 8 8.875 8 7.5 L 8 7 L 6 7 L 6 8 L 6.796875 8 C 6.578125 8.554688 6.136719 9 5.5 9 C 4.664063 9 4 8.335938 4 7.5 C 4 6.664063 4.664063 6 5.5 6 C 5.882813 6 6.222656 6.140625 6.488281 6.371094 L 7.148438 5.621094 C 6.707031 5.234375 6.128906 5 5.5 5 Z M 10 6 L 10 7 L 9 7 L 9 8 L 10 8 L 10 9 L 11 9 L 11 8 L 12 8 L 12 7 L 11 7 L 11 6 Z"/></svg>                      
                    </div> 
                    <div className='flex '>
                     <div className='rounded-full px-2 text-sm border border-white'>Collect</div>                       
                    </div> 
                  </div>
                  <div className='fill-white stroke-white flex justify-end'>
                    <svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1.035156 C 3.917969 1.035156 1 3.941406 1 7.515625 L 1 8 L 2 8 L 2 7.515625 C 2 4.484375 4.457031 2.035156 7.5 2.035156 C 9.132813 2.035156 10.589844 2.75 11.59375 3.875 L 10.464844 5 L 14 5 L 14 1.476563 L 12.300781 3.167969 C 11.113281 1.863281 9.40625 1.035156 7.5 1.035156 Z M 13 7 L 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 5.859375 13 4.402344 12.277344 3.394531 11.140625 L 4.535156 10 L 1 10 L 1 13.535156 L 2.6875 11.847656 C 3.878906 13.164063 5.589844 14 7.5 14 C 11.085938 14 14 11.085938 14 7.5 L 14 7 Z"/></svg>
                  </div>
                </section>
              </div>
              <div className = 'flex flex-col mx-5'>
                <span className='font-serif my-2'>Karina Sirqueira Gallery</span>
                <div className='flex flex-row justify-between'>
                  <span className=' text-xs mb-5'>From United States</span>
                  <span className=' text-xs'>September 11, 2022</span>
                </div>

              </div>
              <div className = 'flex mx-5 ' >
                <Image
                 className='rounded-full overflow-hidden' 
                 src = "/avatar.jpeg"
                 height = {18}
                 width = {32}
                 alt = 'search logo'                 
                />
                <p className='font-serif text-xs my-2 mx-2'>BY KARINA SIRQUEIRA</p>
              </div>
            </div>
            <div className =' group hover:-translate-y-2  flex flex-col divide-y divide-gray-200 w-72 shadow-xl hover:shadow-2xl transition-all duration-300 ease-in-out'>
              <div className = 'relative flex item-center justify-center relative overflow-hidden bg-black '>
                <Image
                 className='scale-100 absolute w-full h-full transition-all duration-300 ease-in-out group-hover:scale-125 group-hover:opacity-50'
                 src = "/mrBeast.png"
                 height = {220}
                 width = {290}
                 alt = 'search logo'               
                />
                <section className='opacity-0 group-hover:opacity-100 flex flex-col absolute justify-between my-5 w-full h-full px-5 pb-10 transition-all duration-300 ease-in-out'>
                  <div className='flex flex-row stroke-white fill-white stroke text-white justify-between' >
                    <div className='flex flex-row '>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.266333 10.967571 12.541024 8.3125 12.933594 L 8.3125 9.0898438 L 9.8652344 9.0898438 L 10.109375 7.5136719 L 8.3125 7.5136719 L 8.3125 6.6503906 C 8.3125 5.9953906 8.5256719 5.4140625 9.1386719 5.4140625 L 10.123047 5.4140625 L 10.123047 4.0371094 C 9.9500469 4.0141094 9.5845781 3.9628906 8.8925781 3.9628906 C 7.4485781 3.9628906 6.6015625 4.7258906 6.6015625 6.4628906 L 6.6015625 7.5117188 L 5.1171875 7.5117188 L 5.1171875 9.0898438 L 6.6035156 9.0898438 L 6.6035156 12.919922 C 3.9897868 12.492118 2 10.237066 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.543488 10.543488 13 7.5 13 C 4.4565116 13 2 10.543488 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z M 9.1113281 4.7519531 C 8.2683281 4.7519531 7.5820312 5.4353438 7.5820312 6.2773438 C 7.5820312 6.4343438 7.6367188 6.5395312 7.6367188 6.6445312 C 6.3727188 6.5925313 5.3229375 5.895 4.5859375 5 C 4.4279375 5.211 4.375 5.4733281 4.375 5.7363281 C 4.375 6.2623281 4.5799531 6.8419375 5.0019531 7.2109375 C 4.7219531 7.1729375 4.586 7.105 4.375 7 C 4.375 7.737 4.8442969 8.2248125 5.5292969 8.3828125 C 5.5292969 8.3828125 5.2654219 8.4355469 5.1074219 8.4355469 C 4.9874219 8.4355469 4.84375 8.3828125 4.84375 8.3828125 C 5.05475 8.9618125 5.580625 9.4335938 6.265625 9.4335938 C 5.739625 9.8025937 5.0541406 10 4.3691406 10 L 4 10 C 4.375 10.5 5.2494063 10.750953 6.3164062 10.751953 C 9.1074063 10.751953 10.636719 8.4355469 10.636719 6.4355469 L 10.636719 6.2246094 C 10.900719 6.0136094 11.163 5.7505469 11.375 5.4355469 C 11.059 5.5935469 10.796469 5.6442656 10.480469 5.6972656 C 10.796469 5.4872656 11.059062 5.2234688 11.164062 4.8554688 C 10.901063 5.0124687 10.585797 5.1716094 10.216797 5.2246094 C 9.9527969 4.9096094 9.5333281 4.7519531 9.1113281 4.7519531 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 4.457031 4.457031 2 7.5 2 Z M 5.5 5 C 4.125 5 3 6.125 3 7.5 C 3 8.875 4.125 10 5.5 10 C 6.875 10 8 8.875 8 7.5 L 8 7 L 6 7 L 6 8 L 6.796875 8 C 6.578125 8.554688 6.136719 9 5.5 9 C 4.664063 9 4 8.335938 4 7.5 C 4 6.664063 4.664063 6 5.5 6 C 5.882813 6 6.222656 6.140625 6.488281 6.371094 L 7.148438 5.621094 C 6.707031 5.234375 6.128906 5 5.5 5 Z M 10 6 L 10 7 L 9 7 L 9 8 L 10 8 L 10 9 L 11 9 L 11 8 L 12 8 L 12 7 L 11 7 L 11 6 Z"/></svg>                      
                    </div> 
                    <div className='flex '>
                     <div className='rounded-full px-2 text-sm border border-white'>Collect</div>                       
                    </div> 
                  </div>
                  <div className='fill-white stroke-white flex justify-end'>
                    <svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1.035156 C 3.917969 1.035156 1 3.941406 1 7.515625 L 1 8 L 2 8 L 2 7.515625 C 2 4.484375 4.457031 2.035156 7.5 2.035156 C 9.132813 2.035156 10.589844 2.75 11.59375 3.875 L 10.464844 5 L 14 5 L 14 1.476563 L 12.300781 3.167969 C 11.113281 1.863281 9.40625 1.035156 7.5 1.035156 Z M 13 7 L 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 5.859375 13 4.402344 12.277344 3.394531 11.140625 L 4.535156 10 L 1 10 L 1 13.535156 L 2.6875 11.847656 C 3.878906 13.164063 5.589844 14 7.5 14 C 11.085938 14 14 11.085938 14 7.5 L 14 7 Z"/></svg>
                  </div>
                </section>
              </div>
              <div className = 'flex flex-col mx-5'>
                <span className='font-serif my-2'>Karina Sirqueira Gallery</span>
                <div className='flex flex-row justify-between'>
                  <span className=' text-xs mb-5'>From United States</span>
                  <span className=' text-xs'>September 11, 2022</span>
                </div>

              </div>
              <div className = 'flex mx-5 ' >
                <Image
                 className='rounded-full overflow-hidden' 
                 src = "/avatar.jpeg"
                 height = {18}
                 width = {32}
                 alt = 'search logo'                 
                />
                <p className='font-serif text-xs my-2 mx-2'>BY KARINA SIRQUEIRA</p>
              </div>
            </div>
            <div className =' group hover:-translate-y-2  flex flex-col divide-y divide-gray-200 w-72 shadow-xl hover:shadow-2xl transition-all duration-300 ease-in-out'>
              <div className = 'relative flex item-center justify-center relative overflow-hidden bg-black '>
                <Image
                 className='scale-100 absolute w-full h-full transition-all duration-300 ease-in-out group-hover:scale-125 group-hover:opacity-50'
                 src = "/mrBeast.png"
                 height = {220}
                 width = {290}
                 alt = 'search logo'               
                />
                <section className='opacity-0 group-hover:opacity-100 flex flex-col absolute justify-between my-5 w-full h-full px-5 pb-10 transition-all duration-300 ease-in-out'>
                  <div className='flex flex-row stroke-white fill-white stroke text-white justify-between' >
                    <div className='flex flex-row '>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.266333 10.967571 12.541024 8.3125 12.933594 L 8.3125 9.0898438 L 9.8652344 9.0898438 L 10.109375 7.5136719 L 8.3125 7.5136719 L 8.3125 6.6503906 C 8.3125 5.9953906 8.5256719 5.4140625 9.1386719 5.4140625 L 10.123047 5.4140625 L 10.123047 4.0371094 C 9.9500469 4.0141094 9.5845781 3.9628906 8.8925781 3.9628906 C 7.4485781 3.9628906 6.6015625 4.7258906 6.6015625 6.4628906 L 6.6015625 7.5117188 L 5.1171875 7.5117188 L 5.1171875 9.0898438 L 6.6035156 9.0898438 L 6.6035156 12.919922 C 3.9897868 12.492118 2 10.237066 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.543488 10.543488 13 7.5 13 C 4.4565116 13 2 10.543488 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z M 9.1113281 4.7519531 C 8.2683281 4.7519531 7.5820312 5.4353438 7.5820312 6.2773438 C 7.5820312 6.4343438 7.6367188 6.5395312 7.6367188 6.6445312 C 6.3727188 6.5925313 5.3229375 5.895 4.5859375 5 C 4.4279375 5.211 4.375 5.4733281 4.375 5.7363281 C 4.375 6.2623281 4.5799531 6.8419375 5.0019531 7.2109375 C 4.7219531 7.1729375 4.586 7.105 4.375 7 C 4.375 7.737 4.8442969 8.2248125 5.5292969 8.3828125 C 5.5292969 8.3828125 5.2654219 8.4355469 5.1074219 8.4355469 C 4.9874219 8.4355469 4.84375 8.3828125 4.84375 8.3828125 C 5.05475 8.9618125 5.580625 9.4335938 6.265625 9.4335938 C 5.739625 9.8025937 5.0541406 10 4.3691406 10 L 4 10 C 4.375 10.5 5.2494063 10.750953 6.3164062 10.751953 C 9.1074063 10.751953 10.636719 8.4355469 10.636719 6.4355469 L 10.636719 6.2246094 C 10.900719 6.0136094 11.163 5.7505469 11.375 5.4355469 C 11.059 5.5935469 10.796469 5.6442656 10.480469 5.6972656 C 10.796469 5.4872656 11.059062 5.2234688 11.164062 4.8554688 C 10.901063 5.0124687 10.585797 5.1716094 10.216797 5.2246094 C 9.9527969 4.9096094 9.5333281 4.7519531 9.1113281 4.7519531 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 4.457031 4.457031 2 7.5 2 Z M 5.5 5 C 4.125 5 3 6.125 3 7.5 C 3 8.875 4.125 10 5.5 10 C 6.875 10 8 8.875 8 7.5 L 8 7 L 6 7 L 6 8 L 6.796875 8 C 6.578125 8.554688 6.136719 9 5.5 9 C 4.664063 9 4 8.335938 4 7.5 C 4 6.664063 4.664063 6 5.5 6 C 5.882813 6 6.222656 6.140625 6.488281 6.371094 L 7.148438 5.621094 C 6.707031 5.234375 6.128906 5 5.5 5 Z M 10 6 L 10 7 L 9 7 L 9 8 L 10 8 L 10 9 L 11 9 L 11 8 L 12 8 L 12 7 L 11 7 L 11 6 Z"/></svg>                      
                    </div> 
                    <div className='flex '>
                     <div className='rounded-full px-2 text-sm border border-white'>Collect</div>                       
                    </div> 
                  </div>
                  <div className='fill-white stroke-white flex justify-end'>
                    <svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1.035156 C 3.917969 1.035156 1 3.941406 1 7.515625 L 1 8 L 2 8 L 2 7.515625 C 2 4.484375 4.457031 2.035156 7.5 2.035156 C 9.132813 2.035156 10.589844 2.75 11.59375 3.875 L 10.464844 5 L 14 5 L 14 1.476563 L 12.300781 3.167969 C 11.113281 1.863281 9.40625 1.035156 7.5 1.035156 Z M 13 7 L 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 5.859375 13 4.402344 12.277344 3.394531 11.140625 L 4.535156 10 L 1 10 L 1 13.535156 L 2.6875 11.847656 C 3.878906 13.164063 5.589844 14 7.5 14 C 11.085938 14 14 11.085938 14 7.5 L 14 7 Z"/></svg>
                  </div>
                </section>
              </div>
              <div className = 'flex flex-col mx-5'>
                <span className='font-serif my-2'>Karina Sirqueira Gallery</span>
                <div className='flex flex-row justify-between'>
                  <span className=' text-xs mb-5'>From United States</span>
                  <span className=' text-xs'>September 11, 2022</span>
                </div>

              </div>
              <div className = 'flex mx-5 ' >
                <Image
                 className='rounded-full overflow-hidden' 
                 src = "/avatar.jpeg"
                 height = {18}
                 width = {32}
                 alt = 'search logo'                 
                />
                <p className='font-serif text-xs my-2 mx-2'>BY KARINA SIRQUEIRA</p>
              </div>
            </div>
            <div className =' group hover:-translate-y-2  flex flex-col divide-y divide-gray-200 w-72 shadow-xl hover:shadow-2xl transition-all duration-300 ease-in-out'>
              <div className = 'relative flex item-center justify-center relative overflow-hidden bg-black '>
                <Image
                 className='scale-100 absolute w-full h-full transition-all duration-300 ease-in-out group-hover:scale-125 group-hover:opacity-50'
                 src = "/mrBeast.png"
                 height = {220}
                 width = {290}
                 alt = 'search logo'               
                />
                <section className='opacity-0 group-hover:opacity-100 flex flex-col absolute justify-between my-5 w-full h-full px-5 pb-10 transition-all duration-300 ease-in-out'>
                  <div className='flex flex-row stroke-white fill-white stroke text-white justify-between' >
                    <div className='flex flex-row '>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.266333 10.967571 12.541024 8.3125 12.933594 L 8.3125 9.0898438 L 9.8652344 9.0898438 L 10.109375 7.5136719 L 8.3125 7.5136719 L 8.3125 6.6503906 C 8.3125 5.9953906 8.5256719 5.4140625 9.1386719 5.4140625 L 10.123047 5.4140625 L 10.123047 4.0371094 C 9.9500469 4.0141094 9.5845781 3.9628906 8.8925781 3.9628906 C 7.4485781 3.9628906 6.6015625 4.7258906 6.6015625 6.4628906 L 6.6015625 7.5117188 L 5.1171875 7.5117188 L 5.1171875 9.0898438 L 6.6035156 9.0898438 L 6.6035156 12.919922 C 3.9897868 12.492118 2 10.237066 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.9160714 1 1 3.9160714 1 7.5 C 1 11.083929 3.9160714 14 7.5 14 C 11.083929 14 14 11.083929 14 7.5 C 14 3.9160714 11.083929 1 7.5 1 z M 7.5 2 C 10.543488 2 13 4.4565116 13 7.5 C 13 10.543488 10.543488 13 7.5 13 C 4.4565116 13 2 10.543488 2 7.5 C 2 4.4565116 4.4565116 2 7.5 2 z M 9.1113281 4.7519531 C 8.2683281 4.7519531 7.5820312 5.4353438 7.5820312 6.2773438 C 7.5820312 6.4343438 7.6367188 6.5395312 7.6367188 6.6445312 C 6.3727188 6.5925313 5.3229375 5.895 4.5859375 5 C 4.4279375 5.211 4.375 5.4733281 4.375 5.7363281 C 4.375 6.2623281 4.5799531 6.8419375 5.0019531 7.2109375 C 4.7219531 7.1729375 4.586 7.105 4.375 7 C 4.375 7.737 4.8442969 8.2248125 5.5292969 8.3828125 C 5.5292969 8.3828125 5.2654219 8.4355469 5.1074219 8.4355469 C 4.9874219 8.4355469 4.84375 8.3828125 4.84375 8.3828125 C 5.05475 8.9618125 5.580625 9.4335938 6.265625 9.4335938 C 5.739625 9.8025937 5.0541406 10 4.3691406 10 L 4 10 C 4.375 10.5 5.2494063 10.750953 6.3164062 10.751953 C 9.1074063 10.751953 10.636719 8.4355469 10.636719 6.4355469 L 10.636719 6.2246094 C 10.900719 6.0136094 11.163 5.7505469 11.375 5.4355469 C 11.059 5.5935469 10.796469 5.6442656 10.480469 5.6972656 C 10.796469 5.4872656 11.059062 5.2234688 11.164062 4.8554688 C 10.901063 5.0124687 10.585797 5.1716094 10.216797 5.2246094 C 9.9527969 4.9096094 9.5333281 4.7519531 9.1113281 4.7519531 z"/></svg>
                      <svg className='mr-2' fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="24px" height="24px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 4.457031 4.457031 2 7.5 2 Z M 5.5 5 C 4.125 5 3 6.125 3 7.5 C 3 8.875 4.125 10 5.5 10 C 6.875 10 8 8.875 8 7.5 L 8 7 L 6 7 L 6 8 L 6.796875 8 C 6.578125 8.554688 6.136719 9 5.5 9 C 4.664063 9 4 8.335938 4 7.5 C 4 6.664063 4.664063 6 5.5 6 C 5.882813 6 6.222656 6.140625 6.488281 6.371094 L 7.148438 5.621094 C 6.707031 5.234375 6.128906 5 5.5 5 Z M 10 6 L 10 7 L 9 7 L 9 8 L 10 8 L 10 9 L 11 9 L 11 8 L 12 8 L 12 7 L 11 7 L 11 6 Z"/></svg>                      
                    </div> 
                    <div className='flex '>
                     <div className='rounded-full px-2 text-sm border border-white'>Collect</div>                       
                    </div> 
                  </div>
                  <div className='fill-white stroke-white flex justify-end'>
                    <svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1.035156 C 3.917969 1.035156 1 3.941406 1 7.515625 L 1 8 L 2 8 L 2 7.515625 C 2 4.484375 4.457031 2.035156 7.5 2.035156 C 9.132813 2.035156 10.589844 2.75 11.59375 3.875 L 10.464844 5 L 14 5 L 14 1.476563 L 12.300781 3.167969 C 11.113281 1.863281 9.40625 1.035156 7.5 1.035156 Z M 13 7 L 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 5.859375 13 4.402344 12.277344 3.394531 11.140625 L 4.535156 10 L 1 10 L 1 13.535156 L 2.6875 11.847656 C 3.878906 13.164063 5.589844 14 7.5 14 C 11.085938 14 14 11.085938 14 7.5 L 14 7 Z"/></svg>
                  </div>
                </section>
              </div>
              <div className = 'flex flex-col mx-5'>
                <span className='font-serif my-2'>Karina Sirqueira Gallery</span>
                <div className='flex flex-row justify-between'>
                  <span className=' text-xs mb-5'>From United States</span>
                  <span className=' text-xs'>September 11, 2022</span>
                </div>

              </div>
              <div className = 'flex mx-5 ' >
                <Image
                 className='rounded-full overflow-hidden' 
                 src = "/avatar.jpeg"
                 height = {18}
                 width = {32}
                 alt = 'search logo'                 
                />
                <p className='font-serif text-xs my-2 mx-2'>BY KARINA SIRQUEIRA</p>
              </div>
            </div>

          </section>
        </section>
      </section>

      <footer className='flex flex-col divide-y divide-gray-200 bg-gray-900 text-white mt-40 font-mono '>
        <section className='mx-20 my-5'>
          <div className='my-5 flex flex-row justify-between'>
            <div className=''>The awards for design, creativity and innovation on the Internet.</div>
            <div className=''>Next Conferences  Amsterdam and Tokyo</div>
          </div>
          <div className='my-5'>
            <ul className='flex flex-row text-sm '>
              <li className='mr-3'>Web Design Courses</li>
              <li className='mr-3'>Directory</li>
              <li className='mr-3'>Jobs</li>
              <li className='mr-3'>About Us</li>
              <li className='mr-3'>Winners</li>
              <li className='mr-3'>Nominees</li>
              <li className='mr-3'>Blog</li>
            </ul>
          </div>
          <div>
            <ul className='flex flex-row'>
              <li className='mr-3 font-sans mb-20'>Follow Us</li>
              <li className='mr-3'>Twitter</li>
              <li className='mr-3'>Facebook</li>
              <li className='mr-3'>Youtube</li>
              <li className='mr-3'>Instagram</li>
              <li className='mr-3'>LinkedIn</li>
              <li className='mr-3'>Pinterest</li>
              <li className='mr-3'>Reddit</li>
              <li className='mr-3'>WhatsApp</li>
            </ul>
          </div>
        </section>
        <section className='mx-20 text-sm'>
          <ul className='my-5 flex flex-row'>
            <li className='mr-3'>Contact Us</li>
            <li className='mr-3'>F.A.Q</li>
            <li className='mr-3'>Cookies Policy</li>
            <li className='mr-3'>Legal Terms</li>
            <li className='mr-3'>Privacy Policy</li>
            <li className='mr-3'>English</li>
            <li className='mr-3'>Private Cloud Stackscale</li>
          </ul>
        </section>
      </footer>
    </div>
  )
}

