import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>AwwardSite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='relative'>
        <nav className='h-16 fixed z-10 top-0 right-0 left-0  '>
          <ul className='flex flex-row h-16 bg-slate-200 divide-x divide-gray-400 shadow-xl'>
            <li className='flex basis-5% grow-0 w-24  justify-center '><Image 
            src = "/menu.svg"
            height = {24}
            width = {24}
            alt = 'menu logo'
            />
            <span className='my-auto font-mono px-2'>MENU</span>
            </li>
            <li className='flex basis-85%  justify-between w-9/12 '>
              <section className='justify-self-start my-auto px-4'>
                <Image
                src = "/search.svg"
                height = {18}
                width = {18}
                alt = 'search logo'
                />
              </section>
              <section className='my-auto '>
                <span className='text-2xl font-serif'> AWWARDSITE.</span>
              </section>
              <section className='my-auto px-4'>
                <p>are you a member?<a className='font-serif text-lg'>Register/Login</a></p>
              </section>
            </li>
            <li className='text-white bg-gray-900 basis-10% grow w-2/12 flex '><p className='m-auto font-mono'>SUBMIT YOUR SITE!</p></li>
          </ul>
        </nav>
      </section>
      
      <section className=''>
      <Image
      src= "/drone2.jpg"
      height = {1080}
      width = {2160}
      alt = "homepage image"
        />
      </section>
      <section>
        <section className='mx-20 my-10'>
          <div>Site of the day.</div>
          <section className='flex flex-row justify-between'>
            <div className ='flex flex-col divide-y divide-gray-300 w-72 bg-gray-200 '>
              <div className = ''>
                <Image
                 src = "/mrBeast.png"
                 height = {290}
                 width = {290}
                 alt = 'search logo'               
                />
              </div>
              <div className = 'flex flex-col mx-5'>
                <span>Karina Sirqueira Gallery</span>
                <span>From United States</span>
              </div>
              <div className = 'flex mx-5' >
                <Image
                 className='rounded-full' 
                 src = "/avatar.jpeg"
                 height = {18}
                 width = {18}
                 alt = 'search logo'                 
                />
                <p>BY KARINA SIRQUEIRA</p>
              </div>
            </div>
            <div className ='flex flex-col divide-y divide-gray-300 w-1/4 bg-gray-200'>
              <div className = ''>
                <Image
                 src = "/search.svg"
                 height = {18}
                 width = {18}
                 alt = 'search logo'               
                />
              </div>
              <div className = 'flex flex-col'>
                <span>Karina Sirqueira Gallery</span>
                <span>From United States</span>
              </div>
              <div className = 'flex' >
                <Image
                 src = "/search.svg"
                 height = {18}
                 width = {18}
                 alt = 'search logo'                 
                />
                <p>BY KARINA SIRQUEIRA</p>
              </div>
            </div>
            <div className ='flex flex-col divide-y divide-gray-300 w-1/4 bg-gray-200'>
              <div className = ''>
                <Image
                 src = "/search.svg"
                 height = {18}
                 width = {18}
                 alt = 'search logo'               
                />
              </div>
              <div className = 'flex flex-col'>
                <span>Karina Sirqueira Gallery</span>
                <span>From United States</span>
              </div>
              <div className = 'flex' >
                <Image
                 src = "/search.svg"
                 height = {18}
                 width = {18}
                 alt = 'search logo'                 
                />
                <p>BY KARINA SIRQUEIRA</p>
              </div>
            </div>
            <div className ='flex flex-col divide-y divide-gray-300 w-1/4 bg-gray-200'>
              <div className = ''>
                <Image
                 src = "/search.svg"
                 height = {18}
                 width = {18}
                 alt = 'search logo'               
                />
              </div>
              <div className = 'flex flex-col'>
                <span>Karina Sirqueira Gallery</span>
                <span>From United States</span>
              </div>
              <div className = 'flex' >
                <Image
                 src = "/search.svg"
                 height = {18}
                 width = {18}
                 alt = 'search logo'                 
                />
                <p>BY KARINA SIRQUEIRA</p>
              </div>
            </div>
          </section>
        </section>
      </section>

      <footer>

      </footer>
    </div>
  )
}

